[package]
name = "interrmitent-failure"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "ansi", "env-filter"] }

poolparty = { path = "../../poolparty/" }
coinflip = "0.1.1"
