[package]
name = "poolparty"
version = "0.1.0"
edition = "2021"
authors = ["Juxhin Dyrmishi Brigjaj<me@digital-horror.com>"]

[dependencies]
tracing = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
